### ISSUE TITLE
配置实例里少个参数

### ISSUE THREAD

**Issue by dongm2ez** [LingxiTeam/ali-opensearch-sdk#1]
'opensearch' => [
        'access_key_id' => env('OPENSEARCH_ACCESS_KEY'),
        'access_key_secret' => env('OPENSEARCH_ACCESS_SECRET'),
        'host' => env('OPENSARCH_HOST'),
       // 杭州公网API地址：http://opensearch-cn-hangzhou.aliyuncs.com
       // 杭州内网API地址：http://intranet.opensearch-cn-hangzhou.aliyuncs.com
      // 北京公网API地址：http://opensearch-cn-beijing.aliyuncs.com
      // 北京内网API地址：http://intranet.opensearch-cn-beijing.aliyuncs.com
        'debug' => env('OPENSEARCH_DEBUG'),
    ],

**Comment by dongm2ez** [comment]
示例

**Comment by sword-jin** [comment]
@dongm2ez 我还以为没有留出配置入口，已加上
