### ISSUE TITLE
filter 函数写错了

### ISSUE THREAD

**Issue by Tairy** [LingxiTeam/ali-opensearch-sdk#3]
https://github.com/LingxiTeam/ali-opensearch-sdk/blob/master/src/ExtendedBuilder.php#L163

这里的 return 应该放在括号外面。

**Comment by sword-jin** [comment]
感谢指出 @Tairy

**Comment by sword-jin** [comment]
https://github.com/LingxiTeam/ali-opensearch-sdk/releases/tag/v0.0.4
