### ISSUE TITLE
opensearch 排序问题

### ISSUE THREAD

**Issue by juckknife** [LingxiTeam/ali-opensearch-sdk#4]
protected function sort(array $orders)
    {
        foreach ($orders as $key => $value) {
            $this->cloudsearchSearch->addSort($value['column'], $value['column'] == 'asc' ? CloudsearchSearch::SORT_INCREASE : CloudsearchSearch::SORT_DECREASE);
        }
    }

addSort 方法中传入的参数 第二个是不是应该换成$value['direction'] 现在排序升序无法起作用。 laravel5.3版本中排序遇到这个问题 麻烦您看下

**Comment by sword-jin** [comment]
@juckknife 最近才看到，是个 bug

**Comment by sword-jin** [comment]
已经修复
